### ISSUE TITLE
Setting for TOUCH_BOTTOM in config.yml is not used?

### ISSUE THREAD

**Issue by pouldam** [pfink/nuimo-openhab-python#6]
I have the bottom touch config commented out:

```
openhab_api_url: "http://192.168.8.10:8090/rest"
nuimo_mac_address: "DD:7F:......"
bluetooth_adapter: hci0
default_gesture_command_mapping:
    #TOUCH_BOTTOM: "OFF"
    #BUTTON_PRESS: "ON"
    BUTTON_RELEASE: "ON"
    TOUCH_RIGHT: "NEXT"
    TOUCH_LEFT: "PREVIOUS"
```
The Nuimo enters sleep mode after a while and to wake it up without sending any commands I touch the bottom. However, when I do that, the Nuimo displays the "pause" symbol. By disabling the bottom touch I would believe that the Nuimo hardware would be woken up, but not display anything. Am I mistaken?
